drop function IF EXISTS trfn_gr17_verificarpeso() CASCADE;
drop function IF EXISTS trfn_gr17_actualizarestadoposicion() CASCADE;
drop function IF EXISTS trfn_gr17_actualizarestadoposicion_salida() CASCADE;
drop function IF EXISTS trfn_gr17_actualizarestadoposicion_interno() CASCADE;
drop function IF EXISTS fn_gr17_getposicioneslibres(date) CASCADE;
drop function IF EXISTS fn_gr17_getmaxpeso(integer, integer) CASCADE;
drop function IF EXISTS fn_gr17_sumapesofila(integer, integer) CASCADE;
drop function IF EXISTS fn_gr17_getclientesanotificar(integer) CASCADE;
drop function IF EXISTS gr17_fn_getcantdias(date, date) CASCADE;
DROP TABLE IF EXISTS GR17_ALQUILER CASCADE;
DROP TABLE IF EXISTS GR17_ALQUILER_POSICIONES CASCADE;
DROP TABLE IF EXISTS GR17_CLIENTE CASCADE; 
DROP TABLE IF EXISTS GR17_ESTANTERIA CASCADE;
DROP TABLE IF EXISTS GR17_FILA CASCADE;
DROP TABLE IF EXISTS GR17_MOVIMIENTO CASCADE;
DROP TABLE IF EXISTS GR17_MOV_ENTRADA CASCADE;
DROP TABLE IF EXISTS GR17_MOV_INTERNO CASCADE;
DROP TABLE IF EXISTS GR17_MOV_SALIDA CASCADE;
DROP TABLE IF EXISTS GR17_PALLET CASCADE;
DROP TABLE IF EXISTS GR17_POSICION CASCADE;